import matplotlib.pyplot as plt
import cv2 as opencv
import numpy as np
import random
import os

import tensorflow.keras as keras
import tensorflow as tf

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
print("Using ", tf.__version__)

matrixvalue = "data/numeral_value.npy"
matrixlabel = "data/numeral_label.npy"
output_model_name = "model.model"

def get_data(values, labels):
    '''
    This method will load the npy arrays that are generated by clean.py
    and it will return it in a tuple
    '''
    values = np.load(values)
    labels = np.load(labels)
    return (values, labels)


def showimageplots():
    '''
    This method is for inspection of numpy data. This will get the numpy array that
    is generated and randomly selects the samples and plots them in the graph
    '''
    values, labels = get_data(matrixvalue, matrixlabel)
    print("Length of training data : %d\nLength of training labels : %d" %
          (len(values), len(labels)))
    grid = 2 # Grid of images required. Default is 2 -> 2 X 2 matrix
    for i in range(1, grid*grid+1):
        index = random.randint(0, len(values))
        plt.subplot(grid, grid, i).set_title(labels[index])
        plt.imshow(values[index], cmap="gray", interpolation="nearest")
    plt.show()


def get_model():
    '''
    This method will define the tensorflow model, compile it and return
    the compiled model
    '''
    model = keras.Sequential([
        keras.layers.Flatten(input_shape=(28, 28)),
        keras.layers.Dense(128, activation=tf.nn.relu),
        keras.layers.Dense(10, activation=tf.nn.softmax)
    ])
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model


def train_model():
    '''
    This method will train the compiled model based on the numpy arrays that is generated
    with values and labels. And then trained model is saved in data/hindi-num.model
    '''
    values, labels = get_data(matrixvalue, matrixlabel)
    values = tf.keras.utils.normalize(values, axis=1)
    model = get_model()
    print(values.shape, labels.shape)
    session = model.fit(values, labels, epochs=20)
    print("----\nTesting\n----")
    history = model.fit(values, labels, epochs=5)
    print("Test Loss :", history)
    print("Test Accuracy :", history)
    model.save("data/%s"%(output_model_name))


def test_model():
    '''
    This method will load the saved model and test the model with randomly fetched
    values from the numpy array and plots them in the graph
    '''
    values, labels = get_data(matrixvalue, matrixlabel)
    saved_model = tf.keras.models.load_model('data/%s'%(output_model_name))
    prediction = saved_model.predict(values)
    grid = 3
    for i in range(1, grid*grid+1):
        index = random.randint(0, len(values))
        plt.subplot(grid, grid, i).set_title(np.argmax(prediction[index]))
        plt.imshow(values[index], cmap="gray", interpolation="nearest")
    plt.show()


train_model() # This will generate the trained model
test_model() # This will load the model and predict the values
